### ISSUE TITLE
Repo clone pulls everything into root of users\user folder

### ISSUE THREAD

**Issue by justoke** [nbarkhina/AzureGitRepos#1]
I've tried this on Windows 10 using VS Code. Everything is fine up until I select the repo to download. I would expect it to clone the repo into a folder with the repo name but the repo and its folders are simply dumped into the root of my user folder. I don't see how to use this extension with this behaviour as the settings don't seem to provide any options to control this.

Any suggestions here? Thank you.

**Comment by justoke** [comment]
I have tried a few things - it basically pulls the repo into whatever folder you open with VS Code. I would say it should run **git clone repo** so that a folder is created with the repo name in whatever folder you prefer. The way it works requires user to create the folder structure first and then download. Wouldn't this be easier?

**Comment by nbarkhina** [comment]
Yes currently it will only run the commands based on where you opened VS Code. However you can customize the commands that it runs, By default it does a **git pull** but you can change it to **git clone** if you like just go to the settings for the extension -

![image](https://user-images.githubusercontent.com/10982154/100523645-fec71680-317f-11eb-9468-0622a25d1e1b.png)

**Comment by justoke** [comment]
Thanks for the prompt reply. I tried that but it says I must provide repo to the command and fails to process the command. What is the command syntax?  I tried Command3 :
git clone

I though the extension would append the repo that I had selected, but it does not:
```
m> git clone
fatal: You must specify a repository to clone.
```

**Comment by nbarkhina** [comment]
Try doing this, set Command1 and Command3 to blank and set Command2 to **git clone** basically it fills in the URL automatically at the end of Command2. So it should look like this - 

![image](https://user-images.githubusercontent.com/10982154/100526182-874fb200-3194-11eb-8783-72cc8d97591d.png)

**Comment by nbarkhina** [comment]
@justoke did that work for you?

**Comment by justoke** [comment]
That worked. This just became one of my favourite extensions. Thank you.

**Comment by nbarkhina** [comment]
awesome thanks!
