### ISSUE TITLE
Target folder for repo cloning

### ISSUE THREAD

**Issue by silasvd** [nbarkhina/AzureGitRepos#4]
The extension clones the repo in the current folder. This could be the user folder or an existing git-folder. Would be nice when you can configure a work directory and automatically create folders for projects and subfolders for repos and show a warning if the target folder is not empty.

At least it should not be possible to clone the repo in a folder which is not empty.

**Comment by nbarkhina** [comment]
you can change that in the settings for the extension, set Command1 to "git clone {{URL}}" and clear out Command2 and Command3 -

![image](https://user-images.githubusercontent.com/10982154/106608949-006fda80-6533-11eb-9c98-bafc8381bbae.png)

**Comment by nbarkhina** [comment]
@silasvd did that help your issue?

**Comment by silasvd** [comment]
Thanks for your answer. I changed the configuration as you suggested. A subfolder for the repository will be created, but it is still always in the current directory I am in. So I changed the command1 to the following, which will open a dialog and ask where to save the repository:

code --open-url -- "vscode://vscode.git/clone?url={{URL}}"

 In addition I set git.defaultCloneDirectory.
